-- require("catppuccin").setup({
-- 	flavour = "mocha",
-- 	transparent_background = true,
--
-- 	custom_highlights = function(colors)
-- 		local background = "#11111b"
-- 		local menu_background = "#181825"
--
-- 		return {
-- 			-- Slight transparency illusion
-- 			Normal = { bg = background },
-- 			NormalFloat = { bg = background },
--
-- 			-- Sidebar/sign column blending
-- 			SignColumn = { bg = background },
-- 			EndOfBuffer = { bg = background },
--
-- 			-- Cursor line
-- 			CursorLine = { bg = colors.surface0 },
--
-- 			-- Floating borders
-- 			FloatBorder = {
-- 				bg = background,
-- 				fg = colors.blue,
-- 			},
--
-- 			-- Completion menu
-- 			Pmenu = { bg = menu_background },
--
-- 			-- Telescope
-- 			TelescopeNormal = {
-- 				bg = background,
-- 			},
--
-- 			TelescopeBorder = {
-- 				bg = background,
-- 				fg = colors.lavender,
-- 			},
-- 		}
-- 	end,
-- })
--
-- vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
vim.cmd("colorscheme catppuccin-mocha")
